#-------------------------------
# Site Settings
title: Kerrie Mariah
logo: #'/images/img2.png'
description: Narrating Nuance, Crafting Concepts, Sparking Solutions
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Work'
      url: '/work/'
    - title: 'Writing'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'
#      submenu:
#      - url: '/elements/'
#        title: 'Elements'


#-------------------------------
# Author Settings
author:
  author__name: Kerrie Mariah
  author__bio: Specializing in crafting innovative web solutions and compelling content
  author__email: kerrie.m.durham@gmail.com
  author__avatar: '/images/img1.png'

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/kerriedurham/"}
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/kerrie.mariah.durham/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/kerrie_mariah/"}
- {icon: "ion-logo-github", link: "https://github.com/KerrieMariah"}


# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Welcome, I am Kerrie Mariah
  hero__description: Self-taught programmer turned corporate finance maven on the bustling trade floors, now the proud founder of my own enterprise. This eclectic professional journey has armed me with a comprehensive skill set, perfectly poised to meet diverse business needs—from innovative web solutions to impactful content, all delivered with a fusion of strategic insight and technological expertise
  hero__image: "/images/01-1.jpg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve worked with some great сompanies

logo__items:
  - name: Quottly
    link: "https://www.quottlyinc.com/"
    image: "/images/quottly.svg"

  - name: Springboard
    link: "https://www.springboard.com/"
    image: "/images/springboard.svg"

  - name: Deutsche Bank
    link: "https://www.pinterest.com/"
    image: "/images/deutsche.svg"

  - name: Murder Mystery Dinner
    link: "https://amurdermysterydinner.com/"
    image: "/images/test.svg"

  - name: RiggingHK
    link: "https://rigginghk.com/"
    image: "/images/rigginghk.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Macquarie_Group_logo.svg/2560px-Macquarie_Group_logo.svg.png"

#-------------------------------
# Newsletter
calendly:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: 
  mailchimp__button__text: Schedule a Free Consultation


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: My Work
  work__description: I offer a diverse array of services, including technical documentation, creative content writing, SEO marketing, and web development, all tailored to support the growth of dynamic businesses.


#-------------------------------
# Testimonials Section
testimonials:
  enable: false

testimonial__title: Clients
testimonial__description:

testimonial__items:
  - name: "Hanna Septimus"
    image: "/images/client-1.jpg"
    designation: "Product Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carla Rosser"
    image: "/images/client-2.jpg"
    designation: "Statistician"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Maria Curtis"
    image: "/images/client-3.jpg"
    designation: "Team Lead"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carter Bergson"
    image: "/images/client-4.jpg"
    designation: "CEO, Founder"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Jordyn Franci"
    image: "/images/client-5.jpg"
    designation: "Personal Trainer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Mira Carder"
    image: "/images/client-6.jpg"
    designation: "Data Scientist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Madelyn Herwitz"
    image: "/images/client-7.jpg"
    designation: "Frontend Engineer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Anika Schleifer"
    image: "/images/client-8.jpg"
    designation: "Fitness Director"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Wilson Dorwart"
    image: "/images/client-9.jpg"
    designation: "Financial Manager"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

#-------------------------------
# P Languages Settings
p_languages:
  enable: true
  p_languages__title: I have extensive experience in the following languages and frameworks

p_languages__items:
  - name: Ruby
    link: 
    image: "/images/ruby-lang-horizontal.svg"

  - name: Java
    link: 
    image: "/images/java-horizontal.svg"

  - name: CSS
    link: 
    image: "/images/w3_css-ar21.svg"

  - name: JavaScript
    link: 
    image: "/images/javascript-horizontal.svg"

  - name: MySQL
    link: 
    image: "/images/mysql-horizontal.svg"

  - name: Macquarie
    link: 
    image: "/images/dotnet-horizontal.svg"

  - name: Macquarie
    link: 
    image: "/images/springio-ar21.svg"

  - name: JavaScript
    link: 
    image: "/images/python-horizontal.svg"

  - name: Macquarie
    link: 
    image: "/images/w3_html5-ar21.svg"

  - name: Macquarie
    link: 
    image: "/images/git-scm-ar21.svg"

  - name: Macquarie
    link: 
    image: "/images/-ImiUh__reactivex.svg"

#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Examples of My Writing
  blog__description:

#-------------------------------
# Certification Settings
certificates:
  enable: true
  certificates__title: A selection of my professional certifications

certificate__items:
  - name: Data Structures
    link: "https://courses.edx.org/certificates/0da1b6ed73ab4d3399a80fb165706138?_gl=1*k81vwr*_ga*MTkyNDMzNjk0NC4xNjk5NDkxODI0*_ga_D3KS4KMDT0*MTY5OTQ5MTgyNC4xLjEuMTY5OTQ5MTgzMi41Mi4wLjA."
    image: "/images/image2vector.svg"

  - name: ReactX
    link: https://www.udemy.com/certificate/UC-4129fd7e-ab7a-4b81-b111-14af2202bb36/
    image: "/images/reactivexcert.svg"

  - name: Algos
    link: 
    image: "/images/algocertprinceton.svg"

#-------------------------------
# Scheduling Settings
scheduling:
  enable: true
  scheduling__title: Schedule a free consultation!

#-------------------------------
# Footer Settings
footer__background__image: "/images/bg.jpg"

#-------------------------------
# Contact Settings
contact:
  email: xknlezda # Add your form_id
  description: Thank you for reaching out! I'll get back to you as soon as I can.  # Add a description of your form
  other_contact_info: You can also reach me at at kerrie.m.durham@gmail.com or on Whatsapp at +85251211421
# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id