#-------------------------------
# Site Settings
title: Kerrie Mariah
logo: # You can add own logo. For example '/images/logo.png'.
description: Narrating Nuance, Crafting Concepts, Sparking Solutions
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
#    - title: 'About'
#      url: '/about/'
    - title: 'Work'
      url: '/work/'
    - title: 'Writing'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'
#      submenu:
#      - url: '/elements/'
#        title: 'Elements'


#-------------------------------
# Author Settings
author:
  author__name: Kerrie Mariah
  author__bio: Specializing in crafting innovative web solutions and compelling content. My journey from coding to finance and back to tech equips me with a unique blend of skills to tackle complex challenges with creativity and precision.
  author__avatar: '/images/img1.png'

social:
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Welcome, I am Kerrie Mariah
  hero__description: Specializing in crafting innovative web solutions and compelling content. My journey from coding to finance and back to tech equips me with a unique blend of skills to tackle complex challenges with creativity and precision
  hero__image: "/images/01-1.jpg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve worked with some great сompanies

logo__items:
  - name: Quottly
    link: "https://www.quottlyinc.com/"
    image: "/images/quottly.svg"

  - name: Springboard
    link: "https://www.springboard.com/"
    image: "/images/springboard.svg"

  - name: Deutsche Bank
    link: "https://www.pinterest.com/"
    image: "/images/deutsche.svg"

  - name: Murder Mystery Dinner
    link: "https://amurdermysterydinner.com/"
    image: "/images/test.svg"

  - name: RiggingHK
    link: "https://rigginghk.com/"
    image: "/images/rigginghk.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Macquarie_Group_logo.svg/2560px-Macquarie_Group_logo.svg.png"

#-------------------------------
# Newsletter
calendly:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: 
  mailchimp__button__text: Schedule a Free Consultation


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: My Work
  work__description: I offer a wide range of services from technical documentation creation, to creative content writing, SEO marketing, as well as web development for growing businesses. 


#-------------------------------
# Testimonials Section
testimonials:
  enable: false

testimonial__title: Clients
testimonial__description:

testimonial__items:
  - name: "Hanna Septimus"
    image: "/images/client-1.jpg"
    designation: "Product Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carla Rosser"
    image: "/images/client-2.jpg"
    designation: "Statistician"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Maria Curtis"
    image: "/images/client-3.jpg"
    designation: "Team Lead"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Carter Bergson"
    image: "/images/client-4.jpg"
    designation: "CEO, Founder"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Jordyn Franci"
    image: "/images/client-5.jpg"
    designation: "Personal Trainer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Mira Carder"
    image: "/images/client-6.jpg"
    designation: "Data Scientist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Madelyn Herwitz"
    image: "/images/client-7.jpg"
    designation: "Frontend Engineer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Anika Schleifer"
    image: "/images/client-8.jpg"
    designation: "Fitness Director"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Wilson Dorwart"
    image: "/images/client-9.jpg"
    designation: "Financial Manager"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve worked with some great сompanies

p_languages__items:
  - name: Ruby
    link: "https://www.ruby-lang.org/en/"
    image: "/images/ruby-lang-horizontal.svg"

  - name: Java
    link: "https://www.springboard.com/"
    image: "/images/java-horizontal.svg"

  - name: CSS
    link: "https://amurdermysterydinner.com/"
    image: "/images/w3_css-ar21.svg"

  - name: JavaScript
    link: "https://rigginghk.com/"
    image: "/images/javascript-horizontal.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/mysql-horizontal.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/dotnet-horizontal.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/springio-ar21.svg"

  - name: JavaScript
    link: "https://rigginghk.com/"
    image: "/images/python-horizontal.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/w3_html5-ar21.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/git-scm-ar21.svg"

  - name: Macquarie
    link: "https://www.macquarie.com/hk.html"
    image: "/images/-ImiUh__reactivex.svg"

#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Writing
  blog__description:


#-------------------------------
# Footer Settings
footer__background__image: "/images/bg.jpg"

#-------------------------------
# Contact Settings
contact:
  email: xknlezda # Add your form_id
  description: Akio comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id